name: Hello YAML Example

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Create Hello World source file"
      - name: create program
        run: echo '#include <iostream>' > hello.cpp && echo >> hello.cpp && echo 'int main() { std::cout << "Hello World!"; return 0; }' >> hello.cpp
      - name: compile program
        run: g++ -o hello hello.cpp
      - name: run program
        run: ./hello

